apiVersion: v1
kind: Service
metadata:
  name: github-actions-hello-app-svc
spec:
  type: NodePort
  selector:
    app: test-git-actions
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 31000
